//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivityLog
    {
        public int LogID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ActivityType { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string Username { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
